import Docker from 'dockerode';

export const docker = new Docker({ socketPath: '/var/run/docker.sock' });

export async function listContainers() {
  const raw = await docker.listContainers({ all: true });
  return Promise.all(raw.map(async (c) => {
    const inspect = await docker.getContainer(c.Id).inspect().catch(() => null);
    const labels = c.Labels || {};
    const composeProject = labels['com.docker.compose.project'] || null;
    const composeService = labels['com.docker.compose.service'] || null;
    const composeFile = labels['com.docker.compose.project.config_files'] || null;
    const composeWorkingDir = labels['com.docker.compose.project.working_dir'] || null;
    const imageRef = c.Image;
    const { repo, tag } = parseImageRef(imageRef);
    const imageId = inspect?.Image || null;
    const created = inspect?.Created || null;
    const startedAt = inspect?.State?.StartedAt || null;
    const health = inspect?.State?.Health?.Status || null;
    const restartCount = inspect?.RestartCount ?? 0;
    const ports = (c.Ports || [])
      .filter(p => p.PublicPort)
      .map(p => `${p.PublicPort}:${p.PrivatePort}/${p.Type}`);
    return {
      id: c.Id,
      shortId: c.Id.slice(0, 12),
      name: (c.Names?.[0] || '').replace(/^\//, ''),
      image: imageRef,
      repo,
      tag,
      imageId,
      state: c.State,
      status: c.Status,
      health,
      created,
      startedAt,
      restartCount,
      ports,
      composeProject,
      composeService,
      composeFile,
      composeWorkingDir,
    };
  }));
}

export async function inspectContainer(idOrName) {
  return docker.getContainer(idOrName).inspect();
}

export async function getLogs(idOrName, tail = 200) {
  const container = docker.getContainer(idOrName);
  const stream = await container.logs({ stdout: true, stderr: true, tail, follow: false, timestamps: false });
  return stripDockerLogHeaders(stream);
}

export async function startContainer(idOrName) {
  await docker.getContainer(idOrName).start();
  return { ok: true };
}

export async function stopContainer(idOrName, timeout = 10) {
  await docker.getContainer(idOrName).stop({ t: timeout });
  return { ok: true };
}

export async function restartContainer(idOrName, timeout = 10) {
  await docker.getContainer(idOrName).restart({ t: timeout });
  return { ok: true };
}

// Build a `docker.createContainer()` options object from a `docker inspect`
// result, preserving the configuration that matters for a standalone
// container: name, image ref, env, command/entrypoint, labels, exposed +
// published ports, volumes/binds, networks (incl. aliases + static IPs),
// and the restart policy (plus the rest of HostConfig verbatim: cap
// add/drop, devices, dns, sysctls, resource limits, etc).
//
// Deliberately NOT preserved / carried over:
//   - The container's identity (Id, hostname derived from Id, MAC addresses,
//     resolv.conf/hosts file contents) — these are regenerated by Docker for
//     the new container, same as `docker compose up -d` does.
//   - Anonymous (unnamed) volumes that aren't reflected in Binds/Mounts —
//     Docker doesn't expose enough info to reliably reattach those, and
//     compose recreation has the same limitation.
//   - `ContainerIDFile` (points at a file tied to the old container's ID).
//   - Live runtime-only state (PIDs, current resource usage, exec sessions).
//
// `overrides.image`, if given, pins the create to a specific image ref
// (e.g. the immutable old image ID) instead of `Config.Image` — used for
// rollback, where we must not resolve a tag that may have moved since.
export function buildRecreateSpec(inspectData, overrides = {}) {
  const Config = inspectData.Config || {};
  const HostConfig = inspectData.HostConfig || {};
  const Networks = inspectData.NetworkSettings?.Networks || {};

  const name = overrides.name || (inspectData.Name || '').replace(/^\//, '');
  const image = overrides.image || Config.Image;

  // Deep-clone HostConfig so we don't mutate the inspect result, and strip
  // fields that reference the old container itself rather than describing
  // desired config.
  const hostConfig = JSON.parse(JSON.stringify(HostConfig));
  delete hostConfig.ContainerIDFile;

  const endpointsConfig = {};
  for (const [netName, net] of Object.entries(Networks)) {
    const entry = {};
    if (net.Aliases?.length) entry.Aliases = net.Aliases;
    if (net.IPAMConfig?.IPv4Address || net.IPAMConfig?.IPv6Address) {
      entry.IPAMConfig = {
        IPv4Address: net.IPAMConfig.IPv4Address || undefined,
        IPv6Address: net.IPAMConfig.IPv6Address || undefined,
      };
    }
    endpointsConfig[netName] = entry;
  }

  return {
    name,
    Image: image,
    Env: Config.Env,
    Cmd: Config.Cmd,
    Entrypoint: Config.Entrypoint,
    Labels: Config.Labels,
    ExposedPorts: Config.ExposedPorts,
    WorkingDir: Config.WorkingDir,
    User: Config.User || undefined,
    Tty: Config.Tty,
    OpenStdin: Config.OpenStdin,
    StopSignal: Config.StopSignal || undefined,
    StopTimeout: Config.StopTimeout,
    Healthcheck: Config.Healthcheck,
    HostConfig: hostConfig,
    NetworkingConfig: Object.keys(endpointsConfig).length ? { EndpointsConfig: endpointsConfig } : undefined,
  };
}

// Re-create a container from its current image, preserving its
// configuration (see buildRecreateSpec). Used to actually apply a
// newly-pulled image to a standalone (non-compose) container, since
// `docker restart` keeps running the image the container was created with.
//
// Sequence: inspect -> stop -> remove -> create -> start. If create/start
// of the new container fails, we make a best-effort attempt to bring the
// *old* container back (pinned to its original immutable image ID, not the
// tag, since the tag may now point at the image we just failed to run) so
// the user isn't left with nothing running. This is best-effort only: no
// snapshotting, no guarantee the rollback container is identical if the
// underlying image was removed from the local store.
export async function recreateContainer(idOrName) {
  const container = docker.getContainer(idOrName);
  const inspectData = await container.inspect();
  const spec = buildRecreateSpec(inspectData);
  // Pin the rollback spec to the exact old image ID so rollback still works
  // even though the tag (Config.Image) may since have moved to the new image.
  const rollbackSpec = buildRecreateSpec(inspectData, { image: inspectData.Image });

  await container.stop({ t: 10 }).catch((e) => {
    if (e.statusCode !== 304) throw e; // 304 = already stopped, fine.
  });
  await container.remove();

  try {
    const created = await docker.createContainer(spec);
    await created.start();
    const after = await created.inspect();
    return { ok: true, id: after.Id, imageId: after.Image };
  } catch (createErr) {
    let rollback;
    try {
      const restored = await docker.createContainer(rollbackSpec);
      await restored.start();
      rollback = { ok: true, id: restored.id };
    } catch (rollbackErr) {
      rollback = { ok: false, error: String(rollbackErr.message || rollbackErr) };
    }

    const message = rollback.ok
      ? `recreate failed: ${createErr.message || createErr}; rolled back to a new container running the previous image`
      : `recreate failed: ${createErr.message || createErr}; rollback also failed: ${rollback.error}`;
    const err = new Error(message);
    err.rollback = rollback;
    err.cause = createErr;
    throw err;
  }
}

export async function pullImage(imageRef) {
  return new Promise((resolve, reject) => {
    docker.pull(imageRef, (err, stream) => {
      if (err) return reject(err);
      const events = [];
      docker.modem.followProgress(stream, (e2, output) => {
        if (e2) return reject(e2);
        resolve({ events: output, summary: output[output.length - 1] });
      }, (event) => events.push(event));
    });
  });
}

export async function execInContainer(idOrName, cmd) {
  const container = docker.getContainer(idOrName);
  const exec = await container.exec({
    Cmd: Array.isArray(cmd) ? cmd : ['sh', '-lc', cmd],
    AttachStdout: true,
    AttachStderr: true,
  });
  const stream = await exec.start({ hijack: true, stdin: false });
  const out = await new Promise((resolve, reject) => {
    const chunks = [];
    stream.on('data', (chunk) => chunks.push(chunk));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);
  });
  const inspect = await exec.inspect();
  return { exitCode: inspect.ExitCode, output: stripDockerLogHeaders(out) };
}

function stripDockerLogHeaders(buf) {
  // Docker multiplexed stream: 8-byte header per chunk (stream type, 0,0,0, 4-byte big-endian length).
  const out = [];
  let i = 0;
  while (i < buf.length) {
    if (buf.length - i < 8) { out.push(buf.slice(i)); break; }
    const len = buf.readUInt32BE(i + 4);
    out.push(buf.slice(i + 8, i + 8 + len));
    i += 8 + len;
  }
  return Buffer.concat(out).toString('utf8');
}

function parseImageRef(ref) {
  // e.g. ghcr.io/danny-avila/librechat:latest -> { repo, tag }
  if (!ref) return { repo: null, tag: null };
  const at = ref.indexOf('@');
  const cleaned = at > -1 ? ref.slice(0, at) : ref;
  const lastColon = cleaned.lastIndexOf(':');
  const lastSlash = cleaned.lastIndexOf('/');
  if (lastColon > lastSlash) {
    return { repo: cleaned.slice(0, lastColon), tag: cleaned.slice(lastColon + 1) };
  }
  return { repo: cleaned, tag: 'latest' };
}
